# action.yml
name: 'run_script'
description: 'run script on the docker image opensuse/leap:15.5'
inputs:
  cmdfile:
    description: 'file to run'
    required: true
    default: 'do'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmdfile }}
